### ISSUE TITLE
Would this be expected to work with any BLE strip?

### ISSUE THREAD

**Issue by retorquere** [Elzizou/script-ledstrip-control#1]
Would this be expected to work with any BLW strip? eg https://www.amazon.nl/LED-strip-veelkleurige-binnenshuis-afstandsbediening-compatibel/dp/B0994FTYYB/ref=sr_1_6?__mk_nl_NL=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=39C2A19ENT0G9&keywords=ble+ledstrip&qid=1646950642&sprefix=ble+ledstrip%2Caps%2C83&sr=8-6 ?

**Comment by sellaziz** [comment]
Hi,
I would say that it should work for some cheap ledstrips. As it seems that many rgb bulbs and ledstrips have the same BLE controller (my ledstrip has the same controller as the bulb from the tutorial listed on the README).
For the ledstrip that you linked,  I think that it would work.

The one that I tested is this one : [link](https://a.aliexpress.com/_mMq1fre)

**Comment by retorquere** [comment]
Cool. How long is the led strip you bought? I see that some cheao led strips show significant brightness drop-off over 3m.

**Comment by sellaziz** [comment]
I bought the 1m one, I did not try led strips over 3m. But I guess that if you use another power supply after the 3m it would be ok (I have tried powering another led strip of 3m with a salvaged power plug that supplies 12V 0.5~1A and it works well).

**Comment by retorquere** [comment]
You can just plug in a PS mid-strip? Did not know that.

**Comment by sellaziz** [comment]
I suppose it would be possible if you cut the power lines in the middle of the strip, feed it with another power supply and connect the controller line between the two cut parts. (or to make sure you have the same voltage/current as the original supply)
